### ISSUE TITLE
Does not support Python 3.7

### ISSUE THREAD

**Issue by swolfe2** [microsoft/dlltracer-python#1]
Hello!

I was sent here from [another incident with a different package](https://github.com/blue-yonder/turbodbc/issues/315). I attempted to install both through the readme and git. However, I encountered issues with both even though I was running as administrator.

Below is what it looks like via terminal in VS Code
![image](https://user-images.githubusercontent.com/36700028/124339761-92315180-db7e-11eb-995e-488b60f00168.png)

**Comment by zooba** [comment]
Yes, we didn't start with 3.7 support. It may be possible to go back and add it - will take a look.

**Comment by zooba** [comment]
Also sorry for the slow reply. Even though I created the repository (through one of our internal tools), I wasn't automatically subscribed to notifications :(

**Comment by swolfe2** [comment]
Hello @zooba, thanks for looking into it!

I can confirm that it's now working:
![image](https://user-images.githubusercontent.com/36700028/129044754-324cdb47-8898-454c-8915-581a36b88fc5.png)
