### ISSUE TITLE
How to build this package?

### ISSUE THREAD

**Issue by gvanem** [microsoft/dlltracer-python#7]
I just discovered `dlltracer` and tried it on a PyCurl example.
It works really nice. Although I didn't like the:
`LoadLibrary \Device\HarddiskVolume3\Windows\System32\kernel.appcore.dll` syntax.
IMHO a `LoadLibrary c:\Windows\System32\kernel.appcore.dll` would be nicer. Possible?

To the issue; the `README.md` doesn't mention how to build it. 
So I looked in `.github/workflows/test.yml` for clues and tried various ways that all failed. (in the `git clone` directory):
 *  `pyproject-build.exe --wheel .` failed with:
 ```
  * Creating virtualenv isolated environment...
  * Installing packages in isolated environment... (Cython, pymsbuild>=1.0.0b6)
  * Getting build dependencies for wheel...
  * Building wheel...
    C:\temp\build-env-qfqufgzl\Scripts\python.exe: No module named cython.__main__; 
   'cython'  is a  package and cannot be directly executed
    C:\temp\build-env-qfqufgzl\lib\site-packages\pymsbuild\targets\cython.targets(54,5): error MSB3073: 
    The command ""C:\temp\build-env-qfqufgzl\Scripts\python.exe" -m cython  -o 
    F:\gv\Python310\Lib\site-packages\dlltracer\Git latest\build\temp\_native.cp310-win_amd64\src\dlltracer\_native.cpp 
   -f -v --cplus F:\gv\Python310\Lib\site-packages\dlltracer\Git latest\src\dlltracer\_native.pyx"
   exited with code 1. [F:\gv\Python310\Lib\site-packages\dlltracer\Git-latest\build\temp\_native.proj]

   ERROR Backend subprocess exited when trying to invoke build_wheel
   ```
   Although I did install/upgraded to the latest versions of Cython + pymsbuild.

* `py.exe -3 -m pymsbuild -v` also failed with the above `No module named cython.__main__` .

* Then trying with `py.exe -3 -m pip install -vvv "git+https://github.com/microsoft/dlltracer-python.git"` which also failed:
```
  Building wheels for collected packages: dlltracer
    Created temporary directory: C:\temp\pip-wheel-h_o60wpu
    Destination directory: C:\temp\pip-wheel-h_o60wpu
    Running command Building wheel for dlltracer (pyproject.toml)

  f:\gv\VC_2022\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The 
  Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues 
  with incremental build. [C:\temp\pip-req-build-w1ibs1je\build\temp\_native.proj]
    F:\gv\Python310\python.exe: No module named cython.__main__; 'cython' is a package and cannot be 
  directly executed
  C:\temp\pip-build-env-hq6p9g50\overlay\Lib\site-packages\pymsbuild\targets\cython.targets(54,5): error MSB3073: 
  The command ""F:\gv\Python310\python.exe" -m cython  -o C:\temp\pip-req-build-w1ibs1je\build\temp\_native.cp310-win_amd64\src\dlltracer\_native.cpp -f -v  --cplus
 C:\temp\pip-req-build-w1ibs1je\src\dlltracer\_native.pyx" exited with code 1. 
[C:\temp\pip-req-build-w1ibs1je\build\temp\_native.proj]  error: subprocess-exited-with-error

  × Building wheel for dlltracer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 
'F:\gv\Python310\python.exe' 'F:\gv\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' 
  build_wheel 'c:\temp\tmp0dgu2c_z'
  cwd: C:\temp\pip-req-build-w1ibs1je
  Building wheel for dlltracer (pyproject.toml) ... error
  ERROR: Failed building wheel for dlltracer
Failed to build dlltracer
ERROR: Could not build wheels for dlltracer, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "F:\gv\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "F:\gv\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "F:\gv\Python310\lib\site-packages\pip\_internal\commands\install.py", line 429, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for dlltracer, which is required to install pyproject.toml-base
d projects
Remote version of pip: 24.0
Local version of pip:  24.0
Was pip installed by pip? True
Removed build tracker: 'C:\\temp\\pip-build-tracker-shx_rvs7'
```

How hard should it be. Arg! What is going on here? Some MSbuild issue or what? 
So I ended up with this `build.bat`:
```
  md build
  cython.exe -o build/_native.cpp -3f --cplus src/dlltracer/_native.pyx

  cl -nologo -MD -W3 -Ot -Zi -wd4244 -wd4551 -Fo./build\_native.obj -I./src -I%PY3_HOME%/include build/_native.cpp
  link -nologo -out:build/_native.pyd -dll -incremental:no -debug build/_native.obj -libpath:%PY3_HOME%/libs python3.lib advapi32.lib
```

that works for me.

*PS.* I have no issue with MSbuild itself from the command-line or via `vcpkg.exe`.
And I have the latest Visual-Studio 17.0 Preview 1.0. I.e. `cl` ver. 14.40.33521.

**Comment by zooba** [comment]
Interesting. It seems like `python -m cython` is finding a different Cython directory other than the one it should be installing? Is it possible that you've got a directory somewhere named `cython` that is on `PYTHONPATH` perhaps? I'm basing that on this error:

```
F:\gv\Python310\python.exe: No module named cython.__main__; 'cython' is a package and cannot be directly executed
```

I just ran a test in a clean checkout with `pip wheel .` and had no issues, so it may be something to do with `pyproject-build`? I don't recognise that tool.

For what it's worth, the build instructions (which I'll add to the readme) will essentially be:
```
<activate virtual environment>
pip install Cython pymsbuild
python -m pymsbuild
$env:PYTHONPATH = (Get-Item .\src)
```

Could you let me know if those work for you or if you have the same issue?

**Comment by zooba** [comment]
You can leave out the virtual environment if you want, but then if you work with multiple projects you may find yourself having to upgrade/downgrade packages whenever you switch. The tooling isn't ideal, but it's usually better for most people than the alternative mess.

**Comment by gvanem** [comment]
> **  work with multiple projects ** 

What do you mean by this? Sure, I have  multiple Py-projects. And they all seems to work w/o any venv.

*PS*. I updated by `.bat`-file for `pytest.exe -vv tests/test_basic.py`. Works fine AFAICS.

But can you please show me the `cython` + `cl` flags used in your build since I fail to get any 
`dlltracer.__doc__` value.  This `py -3 -c "import dlltracer; print(dlltracer.__doc__)"` returns `None` ?!

An oversight?

**Comment by zooba** [comment]
There just isn't any documentation in [`dlltracer\__init__.py`](https://github.com/microsoft/dlltracer-python/blob/main/src/dlltracer/__init__.py), so that's expected. Should probably add some, but it's not caused by build options, just the lack of a docstring in a regular .py file.

> What do you mean by this? Sure, I have multiple Py-projects. And they all seems to work w/o any venv.

The potential problem is when you have two projects that require different sets of packages. For example, if one needed `pymsbuild<1.0` and the other needed `pymsbuild>=1.0`, then you'd have to keep reinstalling the right version whenever you work on each one.

If you haven't run into this problem yet, great! But when you hit it, you'll find that the solution is to create a virtual environment for each project rather than sharing packages between them.
